### ISSUE TITLE
PowerAmpImpulse error

### ISSUE THREAD

**Issue by sp-pinkeye** [brummer10/ModularAmpToolKit.lv2#3]
Get this error when trying to run  on Debian 11 system.

mixbus-8.2.170: ./DSP/gx_resampler.cc:208: float* gx_resample::BufferResampler::process(int32_t, int32_t, float*, int32_t, int32_t*): Assertion `inp_count == 0' failed.

Also crashes Carla .....

**Comment by brummer10** [comment]
Hi
Thanks for reporting, I've forgotten to remove the debug flags. It should be fixed in latest revision.
