### ISSUE TITLE
Only usable with a buffersize = powers of two

### ISSUE THREAD

**Issue by dingodoppelt** [brummer10/ModularAmpToolKit.lv2#4]
Hi,
thanks again for some great sounding plugins!
One issue I have is that the plugins only seem to work with a buffersize = 2<sup>x</sup>
When I loaded my preset on a buffersize of 48 samples (@48000Hz) it sounds all fuzzy and overall very badly.
At the moment I can't tell if all plugins are affected or if it is just "PowerAmpImpulses".
If that's expected behaviour I'd suggest documenting it somewhere, as I designed my preset at a samplerate of 64 samples and was quite surprised to find it not working at samplerates not a power of two.
cheers, Nils

**Comment by brummer10** [comment]
Hi
Well, the convolvers (impulses) needs a buffersize by power of 2. And, the minimum buffersize is 64. The tubes been not restricted in that regard.

**Comment by dingodoppelt** [comment]
Thanks for making that clear. I guess this can be closed then.
